
services:
  # Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: omikunle/ticket-backend:latest
    container_name: ticket-backend
    restart: always
    
    # HOST_PORT : CONTAINER_PORT
    # You will access via http://localhost:5347
    # Your app MUST listen on 9392 inside
    ports:
      - "5347:9392"
      
    env_file:
      - .env 